---
name: Test Docker Images

"on":
  push:
    branches:
      - main
    paths:
      - 'images/ubuntu-slim/**'
      - '.github/workflows/docker-images.yml'
  pull_request:
    paths:
      - 'images/ubuntu-slim/**'
      - '.github/workflows/docker-images.yml'
  workflow_dispatch:


permissions:
  contents: read


jobs:
  test-images:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'releases/') }}

    strategy:
      matrix:
        directory:
          - images/ubuntu-slim

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: ${{ github.head_ref }}

      - name: Run test.sh
        working-directory: ${{ matrix.directory }}
        run: bash ./test.sh
