name: "Tools - Validate JSON Schema"

on:
  push:
    branches: [ "customize" ]
  pull_request:
    branches: [ "customize" ]


jobs:
  validate-json-schema:
    name: Validate JSON Schema
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckJsonSchema.ps1
