name: "Tools - Validate JSON Schema"

on:
  push:
    branches: [ "customize" ]
  pull_request:
    branches: [ "customize" ]


jobs:
  validate-json-schema:
    name: Validate JSON Schema
    runs-on: ubuntu-latest

    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate JSON Schema
        shell: pwsh
        run: ./helpers/CheckJsonSchema.ps1
