---
name: Ubuntu - Trigger collect metadata

"on":
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: true
        type: string        
      container_registry:
        required: false
        type: string
      container_registry_account:
        required: false
        type: string
      container_registry_repo:
        required: false
        type: string
      container_registry_repo_tag_cache_name:
        required: false
        type: string
      container_platform:
        required: false
        type: string

    outputs:
      gh_branch_name:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_branch_name }}
      gh_tag:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_tag }}
      gh_release_title:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_release_title }}
      gh_release_no:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_release_no }}
      gh_pr_title:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_pr_title }}
      gh_pr_labels:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_pr_labels }}
      gh_pr_commit_message:
        value: ${{ jobs.Create-Metadata.outputs.loc_gh_pr_commit_message }}
      hetzner_cloud_packer_hcl_file:
        value: ${{ jobs.Create-Metadata.outputs.loc_hetzner_cloud_packer_hcl_file }}
      hetzner_cloud_object_name:
        value: ${{ jobs.Create-Metadata.outputs.loc_hetzner_cloud_object_name }}
      hetzner_cloud_image_name:
        value: ${{ jobs.Create-Metadata.outputs.loc_hetzner_cloud_image_name }}
      container_registry:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_registry }}
      container_repo:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_repo }}
      container_repo_tag:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_repo_tag }}
      container_repo_cache_tag:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_repo_cache_tag }}
      container_platform:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_platform }}
      container_image_owner:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_image_owner }}
      container_image_version:
        value: ${{ jobs.Create-Metadata.outputs.loc_container_image_version }}
      app_sw_report_file_name:
        value: ${{ jobs.Create-Metadata.outputs.loc_app_sw_report_file_name }}
      app_working_dir:
        value: ${{ jobs.Create-Metadata.outputs.loc_app_working_dir }}
      app_readme_file:
        value: ${{ jobs.Create-Metadata.outputs.loc_app_readme_file }}
      app_sw_sbom_file_name:
        value: ${{ jobs.Create-Metadata.outputs.loc_app_sw_sbom_file_name }}


permissions:
  contents: read


jobs:
  Create-Metadata:
    runs-on: ubuntu-slim
    name: Collect build metadata

    steps:
      - name: Create necessary metadatas
        id: metadata
        shell: bash
        run: |

          # Determines the current date in YYYYMMDD format. Using the Europe/Berlin timezone.
          current_date=$(TZ='Europe/Berlin' date +'%Y%m%d')

          # Formats the GitHub run number to exactly 4 digits and pads missing digits with leading zeros.
          gh_action_run_number=$(printf "%04d" "${GITHUB_RUN_NUMBER}")

          # Contains the current attempt number of the same workflow run. This value increases when the workflow is re-run.
          gh_action_run_attempt=${{ github.run_attempt }}

          # Builds the version string using the format: YYYYMMDD.gh_action_run_number.gh_action_run_attempt. Example: 20260523.0042.1
          version_full=${current_date}.${gh_action_run_number}.${gh_action_run_attempt}

          # Builds the version string using the format: YYYYMMDD.gh_action_run_number. Example: 20260523.0042
          version_long=${current_date}.${gh_action_run_number}

          # Builds the version string using the format: YYYYMMDD. Example: 20260523
          version_short=${current_date}


          # Distribution
          os_dist="ubuntu"
          os_dist_cs="Ubuntu"

          # Architecture
          case "${{ inputs.arch }}" in
            amd64)
              arch_suffix=""
              arch_suffix_cs=""
              arch_suffix_title=""
              ;;
            arm64)
              arch_suffix="-arm64"
              arch_suffix_cs="-Arm64"
              arch_suffix_title=" Arm64"
              ;;
            *)
              echo "Unsupported architecture: ${{ inputs.arch }}"
              exit 1
              ;;
          esac


          # OS
          case "${{ inputs.os }}" in
            ubuntu22)
              os_version="22"
              os_version_cs="22.04"
              app_readme_file="Ubuntu2204${arch_suffix_cs}-Readme.md"
              hcloud_os_image_name="ubuntu-22.04${arch_suffix}"
              hcloud_packer_file_name="ubuntu-22_04${arch_suffix}"
              ;;

            ubuntu24)
              os_version="24"
              os_version_cs="24.04"
              app_readme_file="Ubuntu2404${arch_suffix_cs}-Readme.md"
              hcloud_os_image_name="ubuntu-24.04${arch_suffix}"
              hcloud_packer_file_name="ubuntu-24_04${arch_suffix}"
              ;;

            ubuntu26)
              os_version="26"
              os_version_cs="26.04"
              app_readme_file="Ubuntu${os_version}04${arch_suffix_cs}-Readme.md"
              hcloud_os_image_name="ubuntu-${os_version}.04${arch_suffix}"
              hcloud_packer_file_name="ubuntu-${os_version}_04${arch_suffix}"
              ;;

            ubuntu-slim)
              os_version="slim"
              os_version_cs="Slim"
              app_readme_file="ubuntu-slim-Readme.md"
              app_sw_report_file_name="ubuntu-slim-Report.json"
              app_working_dir="images/ubuntu-slim"
              hcloud_os_image_name="ubuntu-24_04${arch_suffix}"
              hcloud_packer_file_name="ubuntu-24_04.pkl.hcl${arch_suffix}"
              ;;

            *)
              echo "Unsupported OS: ${{ inputs.os }}"
              exit 1
              ;;
          esac


          # Common values
          app_sw_report_file_name="${app_sw_report_file_name:-software-report.json}"
          app_working_dir="${app_working_dir:-images/ubuntu}"
          app_sw_sbom_file_name="sbom.json.zip"
          gh_branch_name="releases/${{ inputs.os }}${arch_suffix}/${version_full}"
          gh_tag="${{ inputs.os }}${arch_suffix}/${version_full}"
          gh_release_title="${os_dist_cs} ${os_version_cs}${arch_suffix_title} (${version_full}) Image Update"
          gh_release_no="${version_full}"
          gh_pr_title="${os_dist_cs} ${os_version_cs}${arch_suffix_title} (${version_full}) Image Update"
          gh_pr_commit_message="Updating readme file for ${{ inputs.os }}${arch_suffix} version ${version_full}"

          hetzner_cloud_object_name="${{ inputs.os }}${arch_suffix}-${version_full}"

          container_repo_tag="${{ inputs.container_registry_account }}/${{ inputs.container_registry_repo }}:${version_full}"
          container_image_version="${version_full}"

          # GitHub labels
          if [ "${{ inputs.os }}" == "ubuntu-slim" ]; then
            gh_pr_labels="OS: ${os_dist_cs},OS: ${os_dist_cs}${os_version_cs},OS: ${os_dist_cs}24"
          else
            gh_pr_labels="OS: ${os_dist_cs},OS: ${os_dist_cs}${os_version},OS: ${os_dist}-${os_version}/${version_long}"
          fi


          # GitHub Outputs
          {
            echo "os_dist=${os_dist}"
            echo "os_dist_cs=${os_dist_cs}"
            echo "os_version=${os_version}"
            echo "os_version_cs=${os_version_cs}"

            echo "app_sw_report_file_name=${app_sw_report_file_name}"
            echo "app_working_dir=${app_working_dir}"
            echo "app_readme_file=${app_readme_file}"
            echo "app_sw_sbom_file_name=${app_sw_sbom_file_name}"
            echo "hcloud_os_image_name=${hcloud_os_image_name}"
            echo "hcloud_packer_file_name=${hcloud_packer_file_name}"
            echo "gh_branch_name=${gh_branch_name}"
            echo "gh_tag=${gh_tag}"
            echo "gh_release_title=${gh_release_title}"
            echo "gh_pr_labels=${gh_pr_labels}"
            echo "gh_release_no=${gh_release_no}"
            echo "gh_pr_title=${gh_pr_title}"
            echo "gh_pr_commit_message=${gh_pr_commit_message}"

            echo "hetzner_cloud_object_name=${hetzner_cloud_object_name}"

            echo "container_repo_tag=${container_repo_tag}"
            echo "container_image_version=${container_image_version}"
          } >> "$GITHUB_OUTPUT"          

    outputs:
      loc_gh_branch_name: "${{ steps.metadata.outputs.gh_branch_name }}"
      loc_gh_tag: "${{ steps.metadata.outputs.gh_tag }}"

      loc_gh_release_title: "${{ steps.metadata.outputs.gh_release_title }}"
      loc_gh_pr_labels: "${{ steps.metadata.outputs.gh_pr_labels }}"
      loc_gh_release_no: "${{ steps.metadata.outputs.gh_release_no }}"

      loc_gh_pr_title: "${{ steps.metadata.outputs.gh_pr_title }}"
      loc_gh_pr_commit_message: "${{ steps.metadata.outputs.gh_pr_commit_message }}"

      loc_hetzner_cloud_object_name: "${{ steps.metadata.outputs.hetzner_cloud_object_name }}"
      loc_hetzner_cloud_image_name: "${{ steps.metadata.outputs.hcloud_os_image_name }}"
      loc_hetzner_cloud_packer_hcl_file: "${{ steps.metadata.outputs.hcloud_packer_file_name }}"

      loc_container_registry: "${{ inputs.container_registry }}"
      loc_container_repo: "${{ inputs.container_registry_account }}/${{ inputs.container_registry_repo }}"
      loc_container_repo_tag: "${{ steps.metadata.outputs.container_repo_tag }}"
      loc_container_platform: "${{ inputs.container_platform }}"
      loc_container_image_owner: "${{ github.repository_owner }}"
      loc_container_image_version: "${{ steps.metadata.outputs.container_image_version }}"
      loc_container_repo_cache_tag: "${{ inputs.container_registry_account }}/${{ inputs.container_registry_repo }}:${{ inputs.container_registry_repo_tag_cache_name }}"

      loc_app_sw_report_file_name: "${{ steps.metadata.outputs.app_sw_report_file_name }}"
      loc_app_working_dir: "${{ steps.metadata.outputs.app_working_dir }}"
      loc_app_readme_file: "${{ steps.metadata.outputs.app_readme_file }}"
      loc_app_sw_sbom_file_name: "${{ steps.metadata.outputs.app_sw_sbom_file_name }}"


  Show-Metadata:
    runs-on: ubuntu-slim
    name: Show build metadata
    needs:
      - Create-Metadata

    steps:
      - name: Display GitHub Repository Default Branch Name
        shell: bash
        run: echo "${{ github.event.repository.default_branch }}"

      - name: Display GitHub Repository Branch Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_branch_name }}"

      - name: Display GitHub Repository Tag Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_tag }}"

      - name: Display GitHub Repository Release Titel
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_release_title }}"

      - name: Display GitHub Repository Versionsnummer
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_release_no }}"

      - name: Display GitHub Repository Pull Request Titel
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_pr_title }}"

      - name: Display GitHub Repository Pull Request Labels
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_pr_labels }}"

      - name: Display GitHub Repository Pull Request Commit Message
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_gh_pr_commit_message }}"


      - name: Display Hetzner Cloud Objekt Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_hetzner_cloud_object_name }}"

      - name: Display Hetzner Cloud Server Image Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_hetzner_cloud_image_name }}"

      - name: Display Github Repository Packer HCL Dateiname
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_hetzner_cloud_packer_hcl_file }}"


      - name: Display Container Registry Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_registry }}"

      - name: Display Container Registry Repository
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_repo }}"

      - name: Display Container Repository Tag
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_repo_tag }}"

      - name: Display Container Repository Cache Tag
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_repo_cache_tag }}"

      - name: Display Container Repository Container Platform
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_platform }}"

      - name: Display Container Repository Container Image Owner
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_image_owner }}"

      - name: Display Container Repository Container Image Version No.
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_container_image_version }}"


      - name: Display App Software Report File Name
        shell: bash      
        run: echo "${{ needs.Create-Metadata.outputs.loc_app_sw_report_file_name}}"

      - name: Display App Working Directory
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_app_working_dir }}"

      - name: Display App Readme File Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_app_readme_file }}"

      - name: Display App SBOM File Name
        shell: bash
        run: echo "${{ needs.Create-Metadata.outputs.loc_app_sw_sbom_file_name }}"
