---
name: Ubuntu - Build docker image for Ubuntu Slim

"on":
  workflow_dispatch:


permissions:
  contents: read


env:
  OS: "ubuntu-slim"

  REGISTRY: ${{ vars.REGISTRY }}
  REGISTRY_ACCOUNT: ${{ vars.REGISTRY_ACCOUNT }}
  REGISTRY_REPO: ${{ vars.REGISTRY_REPO }}
  REGISTRY_REPO_TAG_CACHE_NAME: ${{ vars.REGISTRY_REPO_TAG_CACHE_NAME }}
  REGISTRY_PLATFORMS: ${{ vars.REGISTRY_PLATFORMS }}

  COSIGN_EXPERIMENTAL: "true"

concurrency:
  group: "runner-image-build-${{ github.workflow }}"
  cancel-in-progress: false


jobs:
  Set-Variables:
    runs-on: ubuntu-slim

    permissions:
      contents: read

    steps:
      - name: Check required variables
        shell: bash
        run: |
          missing=0

          for var in \
            REGISTRY \
            REGISTRY_ACCOUNT \
            REGISTRY_REPO \
            REGISTRY_REPO_TAG_CACHE_NAME \
            REGISTRY_PLATFORMS
          do
            if [[ -z "${!var}" ]]; then
              echo "::error::Repository variable '$var' is missing."
              missing=1
            else
              echo "::notice::$var is configured."
            fi
          done

          exit $missing

      - name: Assign ENV variable to workflow variable
        id: env
        run: |
           echo "OS=$OS" >> $GITHUB_OUTPUT

    outputs:
      os: ${{ steps.env.outputs.OS }}


  Trigger-CollectInformations:
    needs:
      - Set-Variables

    permissions:
      contents: read

    uses: ./.github/workflows/ubuntu_trigger_01-collect-metadata.yml
    with:
      os: ${{ needs.Set-Variables.outputs.os }}
      container_registry: ${{ vars.REGISTRY }}
      container_registry_account: ${{ vars.REGISTRY_ACCOUNT }}
      container_registry_repo: ${{ vars.REGISTRY_REPO }}
      container_registry_repo_tag_cache_name: ${{ vars.REGISTRY_REPO_TAG_CACHE_NAME }}
      container_platform: ${{ vars.REGISTRY_PLATFORMS }}


  Trigger-ImageBuilder:
    needs:
      - Trigger-CollectInformations

    permissions:
      contents: write

    uses: ./.github/workflows/ubuntu_trigger_02-build-container.yml
    with:
      gh_branch_name: ${{ needs.Trigger-CollectInformations.outputs.gh_branch_name }}
      gh_tag: ${{ needs.Trigger-CollectInformations.outputs.gh_tag }}
      gh_release_no: ${{ needs.Trigger-CollectInformations.outputs.gh_release_no }}
      gh_pr_commit_message: ${{ needs.Trigger-CollectInformations.outputs.gh_pr_commit_message }}
      app_working_dir: ${{ needs.Trigger-CollectInformations.outputs.app_working_dir }}
      app_sw_report_file_name: ${{ needs.Trigger-CollectInformations.outputs.app_sw_report_file_name }}
      container_registry_name: ${{ needs.Trigger-CollectInformations.outputs.container_registry }}
      container_repo_tag: ${{ needs.Trigger-CollectInformations.outputs.container_repo_tag }}
      container_repo_cache_tag: ${{ needs.Trigger-CollectInformations.outputs.container_repo_cache_tag }}
      container_platform: ${{ needs.Trigger-CollectInformations.outputs.container_platform }}
      cosign_experimental: ${{ vars.COSIGN_EXPERIMENTAL }}

    secrets:
      gh_app_rihc_id: ${{ secrets.GH_APP_RIHC_ID }}
      gh_app_rihc_pk: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}
      container_registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      container_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}


  Trigger-SoftwareReport:
    needs:
      - Trigger-CollectInformations
      - Trigger-ImageBuilder

    permissions:
      contents: read

    uses: ./.github/workflows/ubuntu_trigger_03-report.yml
    with:
      gh_branch_name: ${{ needs.Trigger-CollectInformations.outputs.gh_branch_name }}
      gh_tag: ${{ needs.Trigger-CollectInformations.outputs.gh_tag }}
      app_swrp_file_name: ${{ needs.Trigger-CollectInformations.outputs.app_sw_report_file_name }}
      app_readme_file: ${{ needs.Trigger-CollectInformations.outputs.app_readme_file }}
      app_working_dir: ${{ needs.Trigger-CollectInformations.outputs.app_working_dir }}

    secrets:
      gh_app_rihc_id: ${{ secrets.GH_APP_RIHC_ID }}
      gh_app_rihc_pk: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}


  Trigger-PullRequest:
    needs:
      - Trigger-CollectInformations
      - Trigger-ImageBuilder
      - Trigger-SoftwareReport

    permissions:
      contents: write
      pull-requests: write

    uses: ./.github/workflows/ubuntu_trigger_04-pullrequest.yml
    with:
      gh_branch_name: ${{ needs.Trigger-CollectInformations.outputs.gh_branch_name }}
      gh_pr_title: ${{ needs.Trigger-CollectInformations.outputs.gh_pr_title }}
      gh_pr_body: ${{ needs.Trigger-SoftwareReport.outputs.app_swrp_difference_body }}
      gh_pr_commit_message: ${{ needs.Trigger-CollectInformations.outputs.gh_pr_commit_message }}
      gh_pr_labels: ${{ needs.Trigger-CollectInformations.outputs.gh_pr_labels }}
      gh_release_no: ${{ needs.Trigger-CollectInformations.outputs.gh_release_no }}
      gh_default_branch_name: ${{ github.event.repository.default_branch }}

    secrets:
      gh_app_rihc_id: ${{ secrets.GH_APP_RIHC_ID }}
      gh_app_rihc_pk: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}


  Trigger-Release:
    needs:
      - Trigger-CollectInformations
      - Trigger-ImageBuilder
      - Trigger-SoftwareReport
      - Trigger-PullRequest

    permissions:
      contents: write

    uses: ./.github/workflows/ubuntu_trigger_05-release.yml
    with:
      gh_tag: ${{ needs.Trigger-CollectInformations.outputs.gh_tag }}
      gh_release_title: ${{ needs.Trigger-CollectInformations.outputs.gh_release_title }}
      gh_release_body: ${{ needs.Trigger-SoftwareReport.outputs.app_swrp_difference_body }}
      app_swrp_file_name: ${{ needs.Trigger-CollectInformations.outputs.app_sw_report_file_name }}

    secrets:
      gh_app_rihc_id: ${{ secrets.GH_APP_RIHC_ID }}
      gh_app_rihc_pk: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}


  Trigger-Publish:
    needs:
      - Trigger-CollectInformations
      - Trigger-ImageBuilder
      - Trigger-Release

    permissions:
      contents: read

    uses: ./.github/workflows/ubuntu_trigger_06-publish.yml
    with:
      container_registry_name: ${{ needs.Trigger-CollectInformations.outputs.container_registry }}
      container_repo: ${{ needs.Trigger-CollectInformations.outputs.container_repo }}
      container_repo_tag: ${{ needs.Trigger-CollectInformations.outputs.container_repo_tag }}

    secrets:
      container_registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      container_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}


  Trigger-CleanupOnFailure:
    needs:
      - Trigger-CollectInformations
      - Trigger-ImageBuilder
      - Trigger-SoftwareReport
      - Trigger-PullRequest
      - Trigger-Release

    if: >
      always() &&
      (
        needs.Trigger-ImageBuilder.result != 'success' ||
        needs.Trigger-SoftwareReport.result != 'success' ||
        needs.Trigger-PullRequest.result != 'success' ||
        needs.Trigger-Release.result != 'success'
      )

    permissions:
      contents: write

    uses: ./.github/workflows/ubuntu_trigger_07-cleanup-on-error.yml
    with:
      gh_branch_name: ${{ needs.Trigger-CollectInformations.outputs.gh_branch_name }}    
      gh_tag: ${{ needs.Trigger-CollectInformations.outputs.gh_tag }}
      gh_release_no: ${{ needs.Trigger-CollectInformations.outputs.gh_release_no }}
      hetzner_cloud_object_name: ${{ needs.Trigger-CollectInformations.outputs.hetzner_cloud_object_name }}
      container_repo: ${{ needs.Trigger-CollectInformations.outputs.container_repo }}

    secrets:
      gh_app_rihc_id: ${{ secrets.GH_APP_RIHC_ID }}
      gh_app_rihc_pk: ${{ secrets.GH_APP_RIHC_PRIVATE_KEY }}
      container_registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      container_registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
      hetzner_cloud_token: ${{ secrets.HCLOUD_TOKEN }}
